version: '3.4'
services:
  shipchain-common:
    build:
      context: ../
      target: test
    image: shipchain-common-test
    command: sh -c 'while sleep 3600; do :; done'
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DJANGO_SETTINGS_MODULE=conf.test_settings
