version: '3.4'
services:
  shipchain-common:
    build:
      context: ../
      target: local
    image: shipchain-common-dev
    command: sh -c 'while sleep 3600; do :; done'
    volumes:
      - ../:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1